version: 1.2
workflows:
  - name: trans-window-mvsusie
    subclass: WDL
    primaryDescriptorPath: /workflows/trans_window_mvsusie.wdl
  - name: prepare-trans-window
    subclass: WDL
    primaryDescriptorPath: /workflows/prepare_trans_window.wdl
  - name: ld-pruning
    subclass: WDL
    primaryDescriptorPath: /workflows/ld_pruning.wdl
  - name: transqtl-bam-filtering
    subclass: WDL
    primaryDescriptorPath: /workflows/transqtl_bam_filtering.wdl
  - name: transqtl-mappability
    subclass: WDL
    primaryDescriptorPath: /workflows/transqtl_mappability.wdl
